# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-16 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='poem',
            name='writer',
            field=models.CharField(max_length=5000),
        ),
    ]
